export const FETCH_ACTIVE_PROJECT_SUCCESS = "FETCH_ACTIVE_PROJECT_SUCCESS";
export const FETCH_ACTIVE_PROJECT_EMPTY = "FETCH_ACTIVE_PROJECT_EMPTY";
export const FETCH_ACTIVE_PROJECT_ERROR = "FETCH_ACTIVE_PROJECT_ERROR";

export const FETCH_CLOSED_PROJECT_SUCCESS = "FETCH_CLOSED_PROJECT_SUCCESS";
export const FETCH_CLOSED_PROJECT_EMPTY = "FETCH_CLOSED_PROJECT_EMPTY";
export const FETCH_CLOSED_PROJECT_ERROR = "FETCH_CLOSED_PROJECT_ERROR";
