export const FETCH_UNASSIGNED_ISSUES_SUCCESS =
  "FETCH_UNASSIGNED_ISSUES_SUCCESS";
export const FETCH_UNASSIGNED_ISSUES_EMPTY = "FETCH_UNASSIGNED_ISSUES_EMPTY";
export const FETCH_UNASSIGNED_ISSUES_ERROR = "FETCH_UNASSIGNED_ISSUES_ERROR";

export const FETCH_RESOLVED_ISSUES_SUCCESS = "FETCH_RESOLVED_ISSUES_SUCCESS";
export const FETCH_RESOLVED_ISSUES_EMPTY = "FETCH_RESOLVED_ISSUES_EMPTY";
export const FETCH_RESOLVED_ISSUES_ERROR = "FETCH_RESOLVED_ISSUES_ERROR";

export const FETCH_LAST30DAYS_ISSUES_SUCCESS =
  "FETCH_LAST30DAYS_ISSUES_SUCCESS";
export const FETCH_LAST30DAYS_ISSUES_EMPTY = "FETCH_LAST30DAYS_ISSUES_EMPTY";
export const FETCH_LAST30DAYS_ISSUES_ERROR = "FETCH_LAST30DAYS_ISSUES_ERROR";

export const FETCH_TIMELINE_SUCCESS = "FETCH_TIMELINE_SUCCESS";
export const FETCH_TIMELINE_EMPTY = "FETCH_TIMELINE_EMPTY";
export const FETCH_TIMELINE_ERROR = "FETCH_TIMELINE_ERROR";
