export const POST_PROJECT_SUCCESS = "POST_PROJECT_SUCCESS";
export const POST_PROJECT_ERROR = "POST_PROJECT_ERROR";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_EMPTY = "FETCH_USERS_EMPTY";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const HANDLE_FORM_INPUT_CHANGE = "HANDLE_FORM_INPUT_CHANGE";
