export const POST_ISSUE_SUCCESS = "POST_ISSUE_SUCCESS";
export const POST_ISSUE_ERROR = "POST_ISSUE_ERROR";

export const UPDATE_ISSUE_SUCCESS = "UPDATE_ISSUE_SUCCESS";
export const UPDATE_ISSUE_ERROR = "UPDATE_ISSUE_ERROR";

export const HANDLE_FORM_INPUT_CHANGE = "HANDLE_FORM_INPUT_CHANGE";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_EMPTY = "FETCH_USERS_EMPTY";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
